# docker-compose.prod.yml
services:
  morgans:
    image: morgans
    container_name: morgans
    restart: always
    env_file:
      - .env
    networks:
      - interservices

networks:
  interservices:
    external: true
